### PR TITLE
fixed FFMPEG 5.1 issues

### PR DESCRIPTION
**Pull request by doingharm**
added a couple additions to the fork of dubrsl/gmf to make gmf compatible with FFmpeg 5.1
see issue [3d0c#152](https://github.com/3d0c/gmf/issues/152)

### CODE REVIEW

**Comment by 3d0c** [comment]
Hello. Thank You for contribution. Regarding the code, I guess it won't work with previous versions of FFMpeg.

**Comment by reijnenhhfm** [comment]
> 
Hello. No that's correct it will conflict with previous versions. In ffmpeg 5.1 they changed the names of a couple of classes (don't ask me why) what leads to gmf referring to nonexistent classes when using ffmpeg 5.1. 

I forsee merging the code with the master branch will create issues for other developers not using 5.1.

**Comment by gokalper** [comment]
go.mod is [incorrect](https://github.com/3d0c/gmf/pull/153/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6) preventing downloads of the module:

```
go get github.com/3d0c/gmf
go: downloading github.com/3d0c/gmf v0.0.0-20220906003747-3c1e70196c59
go: github.com/3d0c/gmf@v0.0.0-20220906003747-3c1e70196c59: parsing go.mod:
        module declares its path as: github.com/reijnenhhfm/gmf
                but was required as: github.com/3d0c/gmf
```

**Comment by reijnenhhfm** [comment]
my apologies. fixed this, but i see it's been merged already, so that is no use.

**Comment by gokalper** [comment]
No worries, i issued another PR to address it.

**Pull request merged**
